### ISSUE TITLE
Error: Extension php_sockets is not loaded! You need to enable it in php.ini

### ISSUE THREAD

**Issue by FedericoFedeFede** [AndiSHFR/wake-on-lan.php#1]
I have this error, than i think that this script coldn't work on a hosting service

Error: Extension php_sockets is not loaded! You need to enable it in php.ini

**Comment by AndiSHFR** [comment]
Hello Frederico.

Under what environment do you run this?

- What web server?
- What operation system?
- Under what user is the web server running? 

As stated in the [Caveat](https://github.com/AndiSHFR/wake-on-lan.php#caveat) section it is not running under linux due to limited user permission regarding the raw socket access.

**Comment by leonardocannarella** [comment]
Yes, I've the same problem.
![image](https://user-images.githubusercontent.com/11887620/70782660-d2a46100-1d87-11ea-8cdf-9afc0a2f375b.png)

**Comment by AndiSHFR** [comment]
> 
> 
> Yes, I've the same problem.
> ![image](https://user-images.githubusercontent.com/11887620/70782660-d2a46100-1d87-11ea-8cdf-9afc0a2f375b.png)

As stated in the error message you need to enable the socket extension in the php.ini file.

It looks like you are running this from a linux host and due to access restrictions the usual user the web-server is running the code you will not be able to use the socket functions.
Please see [Caveat](https://github.com/AndiSHFR/wake-on-lan.php#caveat)

I'm running this within a private network on a windows host with [xampp](https://www.apachefriends.org/de/index.html).
