### ISSUE TITLE
Save hosts?

### ISSUE THREAD

**Issue by digpower** [AndiSHFR/wake-on-lan.php#3]
Is there a way to save the hosts that are added without have to import them?

**Comment by AndiSHFR** [comment]
The added computers are saved as a cookie on the web browser. In order to save these settings or to transfer them to another web browser, the export / import function exists.

The aim was to have a personalized list for different people without creating storage functions on the backend and without including a user administration.

Provided that no user administration is implemented and all users see the same list of computers, it is possible to create a simple storage function on the backend, resulting in _one global list_.

Would such a storage of the computer list be sufficient in your sense?

**Comment by tofuSCHNITZEL** [comment]
@digpower check out this branch:
https://github.com/tofuSCHNITZEL/wake-on-lan.php/tree/serverstorage

**Comment by stathious** [comment]
@tofuSCHNITZEL Thanks! Very useful feature indeed.
Unfortunately I get the following error: file "hosts.json" could not be written"
Do I miss something here?

**Comment by tofuSCHNITZEL** [comment]
you probably set write permissions to the folder the script is in by chmod 666 or 777 (on linux)
